version: '3.8'


services:
  consul: 
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - 8500:8500
    command: agent -dev -client=0.0.0.0

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwordv
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh #mount initial script
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    restart: always

  user-service:
    image: user-service
    container_name: user-service
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: usersdb
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      PORT: 5001
      CONSUL_PORT: 8500
      CONSUL_HOST: consul
      APPLICATION_HOST_NAME: user-service
      APPLICATION_SERVICE_NAME: UserService
      KAFKA_HOST: kafka:9092
    ports:
      - "5001:5001"
    depends_on:
      - postgres

volumes:
  postgres_data:

    
    

